services:
  figmatodagautomation:
    image: marcus18781xj/featurely_automator:latest
    env_file:
      - .env
    ports:
      - 6080:6080
      - 3000:3000
    volumes:
      - figmatodagautomation:/app/public
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.app-service.loadbalancer.server.port=3000"
      - "traefik.http.routers.app-router.rule=Host(`merlin.guptaraghav.org`)"
      - "traefik.http.routers.app-router.entrypoints=websecure"
      - "traefik.http.routers.app-router.tls.certresolver=myresolver"
      - "traefik.http.routers.app-router.service=app-service"
      - "traefik.http.services.vnc-service.loadbalancer.server.port=6080"
      - "traefik.http.routers.vnc-router.rule=Host(`vnc.guptaraghav.org`)"
      - "traefik.http.routers.vnc-router.entrypoints=websecure"
      - "traefik.http.routers.vnc-router.tls.certresolver=myresolver"
      - "traefik.http.routers.vnc-router.service=vnc-service"

  traefik:
    image: traefik:v3.1.2
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=raghav@featurely.ai"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      - "traefik_data:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
volumes:
  traefik_data:
  figmatodagautomation:
    driver: local
