services:
  figmatodagautomation:
    image: marcus18781xj/figmatodag:latest
    env_file:
      - .env
    ports:
      - 6080:6080
      - 3000:3000
    volumes:
      - figmatodagautomation:/app/public
volumes:
  figmatodagautomation:
    driver: local
